apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "misskey.fullname" . }}-configuration
  namespace: {{ .Values.namespace }}
data:
  default.yml: |-
    {{ .Files.Get "files/default.yml"|nindent 4 }}
    url: {{ .Values.url }}
    db:
      host: localhost
      port: 5432
      db: misskey
      user: {{ .Values.db_user }}
      pass: {{ .Values.db_pass }}
