apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "misskey.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
  selector:
    {{- include "misskey-postgres.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "misskey.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
  selector:
    {{- include "misskey-redis.selectorLabels" . | nindent 4 }}
