apiVersion: v1
kind: PersistentVolume
metadata:
  name: misskey-postgresql
spec:
  capacity:
    storage: 250Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: misskey-postgresql
  hostPath:
    path: /data/misskey-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-postgresql
  namespace: misskey
spec:
  resources:
    requests:
      storage: 250Gi
  accessModes:
  - ReadWriteMany
  storageClassName: misskey-postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: misskey-files
spec:
  capacity:
    storage: 1000Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: misskey-files
  hostPath:
    path: /media/kingyosun/storage2/misskey-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-files
  namespace: misskey
spec:
  resources:
    requests:
      storage: 1000Gi
  accessModes:
  - ReadWriteMany
  storageClassName: misskey-files
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ai-data
  hostPath:
    path: /data/ai-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-data
  namespace: misskey
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
  - ReadWriteMany
  storageClassName: ai-data
